apiVersion: chisel-operator.io/v1
kind: ExitNode
metadata:
  name: my-exit-node
  namespace: default
spec:
  # IP address of exit node
  host: "192.168.1.1"
  # Control plane socket port
  port: 9090
  # Name of the secret containing the auth key
  # Create a secret with a key named "auth" and put the value there
  # auth: SECRET-NAME
