apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default
  # annotations:
    # chisel-operator.io/exit-node-name: "my-exit-node"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  # annotations:
    # chisel-operator.io/exit-node-name: "my-exit-node"
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

  