apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chisel-operator
subjects:
- kind: ServiceAccount
  name: chisel-operator
  namespace: chisel-operator-system
roleRef:
  kind: ClusterRole
  name: chisel-operator
  apiGroup: rbac.authorization.k8s.io
