apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chisel-operator
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "services/status", "services/finalizers"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["chisel-operator.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
