{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chisel-operator.serviceAccountName" . }}
  labels:
    {{- include "chisel-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chisel-operator.serviceAccountName" . }}
  labels:
    {{- include "chisel-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "services/status", "services/finalizers"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["chisel-operator.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chisel-operator.serviceAccountName" . }}
  labels:
    {{- include "chisel-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
    - kind: ServiceAccount
      name: {{ include "chisel-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "chisel-operator.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io


{{- end }}
