apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: default
spec:
  selector:
    app: test
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: test
    protocol: TCP
    port: 80
    targetPort: 80 