name: Docker

on:
  schedule:
    - cron: "15 14 * * *"
  push:
    paths:
      - "Dockerfile"
      - "src/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - ".dockerignore"
      - ".github/workflows/docker.yml"
    branches: ["main", "staging"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    uses: FyraLabs/actions/.github/workflows/docker.yml@main
    with:
      publish: ${{ github.event_name != 'pull_request' }}
