name: Docker

on:
  schedule:
    - cron: "15 14 * * *"
  push:
    paths:
      - "charts/**"
      
    branches: ["main", "staging"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    uses: appany/helm-oci-chart-releaser@v0.3.0
    with:
      name: chisel-operator
      repository: chisel-operator
      tag: 0.1.0
      path: charts/chisel-operator
      registry: ghcr.io
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      update_dependencies: 'true' # Defaults to false
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
